// <auto-generated />
namespace AngularPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Limits1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Limits1));
        
        string IMigrationMetadata.Id
        {
            get { return "201403291823396_Limits1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
